import './ui/globals.css'



export const metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by create Next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
